experiment:
  name: mdv6_sahi_run1
  output_dir: /content/camtrap-detector-lab/runs
data:
  input_dir: /content/drive/MyDrive/평두메5/testsamples
  video_exts:
  - .MP4
  - .MOV
  preprocess:
    fps: 5
    max_side: 1920
    clip_seconds: null
model:
  name: mdv6
  device: cuda
  conf: 0.1
  version: MDV6-yolov10-c
strategy:
  name: sahi
  tile_size: 640
  overlap: 0.2
  full_frame_pass: true
  nms_iou: 0.5
results:
  save_masks: polygon
  save_viz: false
  push_every_video: true
git:
  enabled: true
  repo_dir: /content/camtrap-detector-lab
  remote: origin
  branch: main
  author_name: JJ1NNU
  author_email: jinwo1111@uos.ac.kr
